/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-03-01 03:54:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/vikra/workspace/BarclaysHackathon/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/barclaysWebApp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.0.2.RELEASE.jar", Long.valueOf(1515223703303L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1515223718468L));
    _jspx_dependants.put("jar:file:/C:/Users/vikra/workspace/BarclaysHackathon/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/barclaysWebApp/WEB-INF/lib/spring-webmvc-5.0.2.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1511758628000L));
    _jspx_dependants.put("jar:file:/C:/Users/vikra/workspace/BarclaysHackathon/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/barclaysWebApp/WEB-INF/lib/spring-webmvc-5.0.2.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1511758628000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<title>Welcome to Barclays site</title>\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-      BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\"\n");
      out.write("\tintegrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"\n");
      out.write("\tintegrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\"\n");
      out.write("\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\t\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\tvar uName = \"\";\n");
      out.write("\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\t\tvar temp = '");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\tconsole.log(temp);\n");
      out.write("\t\t//\t\talert(encodeURIComponent(temp));\n");
      out.write("\t\t$.getJSON(temp, {\n");
      out.write("\t\t\tajax : 'true'\n");
      out.write("\t\t}, function(data) {\n");
      out.write("\t\t\tconsole.log(data[0]);\n");
      out.write("\t\t\t$(\"#userNameAnchor\").text(\"Hi \" + data[0]);\n");
      out.write("\t\t\tuName = data[0];\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$(document)\n");
      out.write("\t\t\t.ready(\n");
      out.write("\t\t\t\t\tfunction() {\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t$('a[name=\"view_balance_anchor\"]')\n");
      out.write("\t\t\t\t\t\t\t\t.click(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(event) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar temp = '");
      if (_jspx_meth_spring_005furl_005f1(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(temp);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//\t\talert(encodeURIComponent(temp));\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#View_Balance\").text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"Fetching Balance...\");\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.getJSON(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttemp,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tajax : 'true'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction(data) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(data[0]);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#View_Balance\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Balance is: \"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[0]);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.fail(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#View_Balance\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Failed to Fetch Balance\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t$('#transferFunds')\n");
      out.write("\t\t\t\t\t\t\t\t.click(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(event) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar temp = '");
      if (_jspx_meth_spring_005furl_005f2(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(temp);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//\t\talert(encodeURIComponent(temp));\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.getJSON(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttemp,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tajax : 'true'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction(data) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(data[0]);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tif (data[0] == \"1\") {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"Funds Successfully transferred\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"Some Error Occured\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.done(function() {\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.fail(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talert(\"Some Error Occured\");\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t$('a[name=\"view_account_anchor\"]')\n");
      out.write("\t\t\t\t\t\t\t\t.click(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(event) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar temp = '");
      if (_jspx_meth_spring_005furl_005f3(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(temp);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//\t\talert(encodeURIComponent(temp));\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#View_Account\").text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"Fetching AccountNo...\");\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.getJSON(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttemp,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tajax : 'true'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction(data) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tconsole\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.log(data[0]);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#View_Account\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Your Account Number is : \"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ data[0]);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.fail(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#View_Account\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Failed to Fetch Account Number\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t$('a[name=\"history_anchor\"]')\n");
      out.write("\t\t\t\t\t\t\t\t.click(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(event) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar temp = '");
      if (_jspx_meth_spring_005furl_005f4(_jspx_page_context))
        return;
      out.write("';\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(temp);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//\t\talert(encodeURIComponent(temp));\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$(\"#Transaction_History\").text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\"Fetching Transaction History...\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar html =\"<table style='width:100%; border: 1px solid black;''>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thtml+=\"<tr><th>Sender Account</th>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<th>Receiver Account</th>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<th>Date</th>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<th>Time</th></tr>\";\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t$\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.getJSON(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttemp,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tajax : 'true'\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction(data) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar i = 0;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvar len = data.length;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfor (i=0; i < len; i++) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<tr>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml += data[i].accNo;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml += data[i].toAccNo;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml += data[i].date;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"<td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml += data[i].time;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"</td>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"</tr>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml+=\"</table>\";\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.done(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#Transaction_History\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thtml);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t})\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t.fail(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"#Transaction_History\")\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.text(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"Failed to Fetch Account Number\");\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\tfunction View_Balance() {\n");
      out.write("\n");
      out.write("\t\tvar x = document.getElementById(\"View_Balance\");\n");
      out.write("\t\t//    b.addEventListener(\"click\",View_Balance,false);;\n");
      out.write("\t\tif (x.style.display == \"none\") {\n");
      out.write("\t\t\tdocument.getElementById(\"Transaction_History\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"Transfer_Funds\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"View_Account\").style.display = \"none\";\n");
      out.write("\t\t\tx.style.display = \"block\";\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tx.style.display = \"none\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction Transaction_History() {\n");
      out.write("\t\tvar x = document.getElementById(\"Transaction_History\");\n");
      out.write("\t\tif (x.style.display == \"none\") {\n");
      out.write("\t\t\tdocument.getElementById(\"View_Balance\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"Transfer_Funds\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"View_Account\").style.display = \"none\";\n");
      out.write("\t\t\tx.style.display = \"block\";\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tx.style.display = \"none\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction Transfer_Funds() {\n");
      out.write("\t\tvar x = document.getElementById(\"Transfer_Funds\");\n");
      out.write("\t\tif (x.style.display == \"none\") {\n");
      out.write("\t\t\tdocument.getElementById(\"Transaction_History\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"View_Balance\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"View_Account\").style.display = \"none\";\n");
      out.write("\t\t\tx.style.display = \"block\";\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tx.style.display = \"none\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction View_Account() {\n");
      out.write("\t\tvar x = document.getElementById(\"View_Account\");\n");
      out.write("\t\tif (x.style.display == \"none\") {\n");
      out.write("\t\t\tdocument.getElementById(\"Transaction_History\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"View_Balance\").style.display = \"none\";\n");
      out.write("\t\t\tdocument.getElementById(\"Transfer_Funds\").style.display = \"none\";\n");
      out.write("\t\t\tx.style.display = \"block\";\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tx.style.display = \"none\";\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\t\n");
      out.write("\t\ttable.inner tr:nth-child(odd) {background-color: #ffffff}\n");
      out.write("\t\ttable.outer tr:nth-child(odd) {background-color: #ffffff}\n");
      out.write("\t\ttable.inner\n");
      out.write("\t\t{\n");
      out.write("   \t\t width: 100%;\n");
      out.write("\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\ttable.inner td \t\n");
      out.write("\t\t{\n");
      out.write("    \t\t  padding: 15px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\ttable.outer td \t\n");
      out.write("\t\t{\n");
      out.write("    \t\t  padding: 15px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\ttable.outer \n");
      out.write("\t\t{\n");
      out.write("    \t\t width: 200%;\n");
      out.write("\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\ttable.outer td\n");
      out.write("\t\t{\n");
      out.write("\t\t text-align:center;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<link\n");
      out.write("\t\thref=\"//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\"\n");
      out.write("\t\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\t<!--Nav bar code-->\n");
      out.write("\t<nav class=\"navbar navbar-inverse container\" role=\"navigation\">\n");
      out.write("\t\t<div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">Barclays.com</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-center\">\n");
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" id=\"userNameAnchor\"\n");
      out.write("\t\t\t\t\t\tclass=\"dropdown-toggle\" data-toggle=\"dropdown\">Hi <b\n");
      out.write("\t\t\t\t\t\t\tclass=\"caret\"></b></a>\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t<li align=\"center\" class=\"well\">\n");
      out.write("\t\t\t\t\t\t\t\t<!-- class well adds a rounded border around an elemen--> <a\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"btn btn-sm btn-default\"><span\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-out\"></span> Logout</a>\n");
      out.write("\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t<!--li dropdwon end-->\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<!--navbarend-->\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /.container-fluid -->\n");
      out.write("\t</nav>\n");
      out.write("\t<!--nav bar code end-->\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t<div class=\"row well\">\n");
      out.write("\t\t\t<div class=\"col-md-2 \">\n");
      out.write("\t\t\t\t<ul class=\"nav nav-pills nav-stacked\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a name=\"view_account_anchor\"\n");
      out.write("\t\t\t\t\t\thref=\"javascript:View_Account()\"><span class=\"glyphicon \"></span>\n");
      out.write("\t\t\t\t\t\t\tView Account</a></li>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a name=\"view_balance_anchor\"\n");
      out.write("\t\t\t\t\t\thref=\"javascript:View_Balance()\"><span class=\"glyphicon \"></span>\n");
      out.write("\t\t\t\t\t\t\tView Balance</a></li>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a name=\"transfer_funds_anchor\"\n");
      out.write("\t\t\t\t\t\thref=\"javascript:Transfer_Funds()\"><span class=\"glyphicon \"></span>\n");
      out.write("\t\t\t\t\t\t\tTransfer Funds</a></li>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a name=\"history_anchor\"\n");
      out.write("\t\t\t\t\t\thref=\"javascript:Transaction_History()\"><span\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon \"></span> Transaction History</a></li>\n");
      out.write("\t\t\t\t\t<br>\n");
      out.write("\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!--class col end-->\n");
      out.write("\t\t\t<div class=\"col-md-10\">\n");
      out.write("\t\t\t\t<div id=\"View_Account\" style=\"display: :none;\">\n");
      out.write("\t\t\t\t\tAccount No is :: <br />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"View_Balance\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t<h5>Balance is ::</h5>\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"Transaction_History\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t<h5>Transaction History is ::</h5>\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t\t<br />\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div id=\"Transfer_Funds\" style=\"display: none;\">\n");
      out.write("\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t<form action=\"\">\n");
      out.write("\t\t\t\t\t\t\t<label for=\"toaccount\"><b>Transfer to Account </b></label> <input\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"text\" id=\"toAccount\" name=\"toaccount\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter account no to transfer\" pattern=\"[0-9]{3}\"><br />\n");
      out.write("\t\t\t\t\t\t\t<br /> <label for=\"tamount\"><b>Transfer amount </b></label> <input\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"number\" id=\"amount\" name=\"tamount\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter amount to be transfered\"><br />\n");
      out.write("\t\t\t\t\t\t\t<br /> <label for=\"cpassword\"><b>Enter Password </b></label> <input\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"password\" id=\"myPassword\" name=\"cpassword\"\n");
      out.write("\t\t\t\t\t\t\t\tplaceholder=\"Enter password\"><br />\n");
      out.write("\t\t\t\t\t\t\t<br /> <input id=\"transferFunds\" type=\"button\" value=\"Submit\"></input>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\t\t\t<br />\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /WEB-INF/jsp/user_page.jsp(46,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/getuName.json");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f1 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f1_reused = false;
    try {
      _jspx_th_spring_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f1.setParent(null);
      // /WEB-INF/jsp/user_page.jsp(65,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f1.setValue("/getBalance/'+uName+'.json");
      int[] _jspx_push_body_count_spring_005furl_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f1 = _jspx_th_spring_005furl_005f1.doStartTag();
        if (_jspx_th_spring_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f1);
      _jspx_th_spring_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f2 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f2_reused = false;
    try {
      _jspx_th_spring_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f2.setParent(null);
      // /WEB-INF/jsp/user_page.jsp(99,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f2.setValue("/transfer/'\n													+ $('#toAccount').val()\n													+ '/'\n													+ $('#amount').val()\n													+ '/'\n													+ $('#myPassword').val()\n													+ '.json");
      int[] _jspx_push_body_count_spring_005furl_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f2 = _jspx_th_spring_005furl_005f2.doStartTag();
        if (_jspx_th_spring_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f2);
      _jspx_th_spring_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f3 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f3_reused = false;
    try {
      _jspx_th_spring_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f3.setParent(null);
      // /WEB-INF/jsp/user_page.jsp(137,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f3.setValue("/getAccountNo.json");
      int[] _jspx_push_body_count_spring_005furl_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f3 = _jspx_th_spring_005furl_005f3.doStartTag();
        if (_jspx_th_spring_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f3);
      _jspx_th_spring_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f4 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f4_reused = false;
    try {
      _jspx_th_spring_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f4.setParent(null);
      // /WEB-INF/jsp/user_page.jsp(171,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f4.setValue("/getTransactionHistory.json");
      int[] _jspx_push_body_count_spring_005furl_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f4 = _jspx_th_spring_005furl_005f4.doStartTag();
        if (_jspx_th_spring_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f4);
      _jspx_th_spring_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spring_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_spring_005furl_005f4_reused);
    }
    return false;
  }
}
